parking/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :spots

  resources :vendors do
    resources :spots
  end

  resources :customers do
    resources :spots
  end
  root "spots#index"

  get "/no_access", to: "spots#no_access"

  # get 'customers/:customer_id/spots/:id' => 'spots#update'
end

# Prefix Verb   URI Pattern                                      Controller#Action
# new_user_session GET    /users/sign_in(.:format)                         devise/sessions#new
# user_session POST   /users/sign_in(.:format)                         devise/sessions#create
# destroy_user_session DELETE /users/sign_out(.:format)                        devise/sessions#destroy
# user_password POST   /users/password(.:format)                        devise/passwords#create
# new_user_password GET    /users/password/new(.:format)                    devise/passwords#new
# edit_user_password GET    /users/password/edit(.:format)                   devise/passwords#edit
#        PATCH  /users/password(.:format)                        devise/passwords#update
#        PUT    /users/password(.:format)                        devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                          devise/registrations#cancel
# user_registration POST   /users(.:format)                                 devise/registrations#create
# new_user_registration GET    /users/sign_up(.:format)                         devise/registrations#new
# edit_user_registration GET    /users/edit(.:format)                            devise/registrations#edit
#        PATCH  /users(.:format)                                 devise/registrations#update
#        PUT    /users(.:format)                                 devise/registrations#update
#        DELETE /users(.:format)                                 devise/registrations#destroy
#  spots GET    /spots(.:format)                                 spots#index
#        POST   /spots(.:format)                                 spots#create
# new_spot GET    /spots/new(.:format)                             spots#new
# edit_spot GET    /spots/:id/edit(.:format)                        spots#edit
#   spot GET    /spots/:id(.:format)                             spots#show
#        PATCH  /spots/:id(.:format)                             spots#update
#        PUT    /spots/:id(.:format)                             spots#update
#        DELETE /spots/:id(.:format)                             spots#destroy
# vendor_spots GET    /vendors/:vendor_id/spots(.:format)              spots#index
#        POST   /vendors/:vendor_id/spots(.:format)              spots#create
# new_vendor_spot GET    /vendors/:vendor_id/spots/new(.:format)          spots#new
# edit_vendor_spot GET    /vendors/:vendor_id/spots/:id/edit(.:format)     spots#edit
# vendor_spot GET    /vendors/:vendor_id/spots/:id(.:format)          spots#show
#        PATCH  /vendors/:vendor_id/spots/:id(.:format)          spots#update
#        PUT    /vendors/:vendor_id/spots/:id(.:format)          spots#update
#        DELETE /vendors/:vendor_id/spots/:id(.:format)          spots#destroy
# vendors GET    /vendors(.:format)                               vendors#index
#        POST   /vendors(.:format)                               vendors#create
# new_vendor GET    /vendors/new(.:format)                           vendors#new
# edit_vendor GET    /vendors/:id/edit(.:format)                      vendors#edit
# vendor GET    /vendors/:id(.:format)                           vendors#show
#        PATCH  /vendors/:id(.:format)                           vendors#update
#        PUT    /vendors/:id(.:format)                           vendors#update
#        DELETE /vendors/:id(.:format)                           vendors#destroy
# customer_spots GET    /customers/:customer_id/spots(.:format)          spots#index
#        POST   /customers/:customer_id/spots(.:format)          spots#create
# new_customer_spot GET    /customers/:customer_id/spots/new(.:format)      spots#new
# edit_customer_spot GET    /customers/:customer_id/spots/:id/edit(.:format) spots#edit
# customer_spot GET    /customers/:customer_id/spots/:id(.:format)      spots#show
#        PATCH  /customers/:customer_id/spots/:id(.:format)      spots#update
#        PUT    /customers/:customer_id/spots/:id(.:format)      spots#update
#        DELETE /customers/:customer_id/spots/:id(.:format)      spots#destroy
# customers GET    /customers(.:format)                             customers#index
#        POST   /customers(.:format)                             customers#create
# new_customer GET    /customers/new(.:format)                         customers#new
# edit_customer GET    /customers/:id/edit(.:format)                    customers#edit
# customer GET    /customers/:id(.:format)                         customers#show
#        PATCH  /customers/:id(.:format)                         customers#update
#        PUT    /customers/:id(.:format)                         customers#update
#        DELETE /customers/:id(.:format)                         customers#destroy
#   root GET    /                                                spots#index

parking/app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :spots
  has_many :vendors, :through => :spots

end

parking/app/models/spot.rb
class Spot < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  geocoded_by :address
  after_validation :geocode,
    :if => lambda{ |obj| obj.address_changed? }
  belongs_to :customer
  belongs_to :vendor
end

parking/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
end

parking/app/models/vendor.rb
class Vendor < ActiveRecord::Base
  has_many :spots
  has_many :customers, :through => :spots
end

parking/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

parking/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :return_customer, only: [:show, :edit, :update, :destroy]

  def index
    @spots = Spot.all
  end

  def show
    @spots = Spot.all
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    @customer.save
    redirect_to("/")
  end

  def update


  end

  private

  def return_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :make, :model)
  end


end

parking/app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :return_spot, only: [:show, :edit, :reserve, :update, :destroy]

  def index
    @spots = Spot.all

  end

  def show
    if !@customer
      @spot = Spot.find(params[:id])
    else
    @customer = Customer.find(params[:customer_id])
  end
  end

  def new
    @vendor = Vendor.find(params[:vendor_id])
    @spot = Spot.new
  end

  def create
    vendor = Vendor.find(params[:vendor_id].to_i)
    @spot = Spot.new(spot_params)

    if @spot.save
        vendor.spots << @spot
        redirect_to "/spots"
    else
        render :root
    end
  end

  def update
    customer = Customer.find(params[:customer_id].to_i)
    @spots.update(available: false)

    if @spots.save
        customer.spots << @spots
        redirect_to "/spots"
    end
  end


  end

  private

  def return_spot
    @spots = Spot.find(params[:id])
  end

  def spot_params
    params.require(:spot).permit(:address, :zipcode, :available, :price, :description, :image)
  end

parking/app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :return_vendor, only: [:show, :edit, :update, :destroy]


  def show
    
  end

  def new
    @vendor = Vendor.new
  end

  def create
    @vendor = Vendor.new(vendor_params)
    @vendor.save
    redirect_to("/")
  end



  private

  def return_vendor
    @vendor = Vendor.find(params[:id])
  end

  def vendor_params
    params.require(:vendor).permit(:first_name, :last_name)
  end

end

parking/app/helpers/application_helper.rb
module ApplicationHelper
end

parking/app/views/customers/index.html.erb
<p>
  <%= @customer.first_name %>
  <%= @customer.last_name %>
  <%= @customer.make %>
  <%= @customer.model %>
</p>


this is the index page
<p>

<% @spots.each do |spot| %>
  <a href="/customers/<%= @customer.id %>/spots/<%=spot.id %>"><%= spot.address%>
  <%= spot.zipcode %>
  <%= spot.price %>
  <%= spot.description %></a>
</p>

<% end %>

parking/app/views/customers/new.html.erb
<div class="container">
<div class="row">
  <div class="col-md-6">
    <h2>Reserve your spot!</h2>
    <%= bootstrap_form_for @customer do |form| %>
    <div class="row">
      <div class="form-group col-lg-6">
        <%= form.text_field :first_name, label: "First Name" %></br>
        <%= form.text_field :last_name, label: "Last Name" %></br>
    </div>
    </div>
      <div class="row">
      <div class="form-group col-lg-6">
        <%= form.text_field :make, label: "Make of Vehicle"%></br>
        <%= form.text_field :model, label: "Model of Vehicle" %></br>
        <%= form.hidden_field :id, :value => current_user.id %>
      </div>
      </div>
      <div class="row">
      <div class="form-group col-lg-6">
      <%= form.submit %>
      <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <h2>Why we need this information...</h2>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
  </div>
</div>

parking/app/views/customers/show.html.erb
<p>
  <%= @customer.first_name %>
  <%= @customer.last_name %>
  <%= @customer.make %>
  <%= @customer.model %>
</p>



this is the show page

<p>

<% @spots.each do |spot| %>
  <a href="/customers/<%= @customer.id %>/spots/<%=spot.id %>"><%= spot.address%>
  <%= spot.zipcode %>
  <%= spot.price %>
  <%= spot.description %></a>
</p>

<% end %>

parking/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Parking</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="http://code.jquery.com/jquery-2.2.0.min.js" charset="utf-8"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Plott</a>
      </div>
      <ul class="nav navbar-nav nav pull-right">
      <% if user_signed_in? %>
       <li>
         <%= link_to "Browse", root_path, :class => 'navbar-link'  %>
       </li>
       <% if current_user %>
       <li>
         <a href="/vendors/<%=current_user.id%>/spots/new" class="navbar-link">Create a Listing</a>
      </li>
      <li>
         <a href="/customers/new" class="navbar-link">Reserve a spot!</a>
         <% else %>
         <% end %>
       </li>
       <li class="dropdown">
         <a class="dropdown-toggle" data-toggle="dropdown" href="/spots">My Account
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
            </li>
            <li>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
              <% else %>
            </li>
            <li>
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
            </li>
            <li>
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
              <% end %>
            </li>
          </ul>
       </li>
      </ul>
    </div>
  </nav>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>

</body>
</html>

parking/app/views/spots/index.html.erb
<head>
  <script src="//maps.google.com/maps/api/js?v=3.22&libraries=geometry&language=&hl=&region="></script>
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
  <link href='http://fonts.googleapis.com/css?family=Oleo+Script' rel='stylesheet' type='text/css'>
</head>

<div class="container-fluid">
<h1>Welcome to <b>Plott</b></h1>
<div class="row">
<div class="col-md-4">
<h2>Available spots in NYC</h2>

<% @spots.each do |spot| %>
  <% if spot.available == false %>
    <% else %>
  <ul>
    <% if current_user %>
    <li>
      <a href="/customers/<%=current_user.id%>/spots/<%= spot.id %>">
      <% else %>
      <a href="/spots/<%= spot.id %>">
      <% end %>
    <%= spot.address %>,
    <%= spot.zipcode %>,
    $<%= spot.price %>
  </li>
</ul></a>
  <% end %>
  <% end %>
</div>
<div class="col-md-8">
  <h2>Map Listings</h2>
  <p>
    Click on marker for more info
  </p>
<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>
<% @spots.each do |spot| %>
  <% if spot.available == false %>
  <% else %>
<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({
  provider: {
    disableDefaultUI: true,
    maxZoom: null
    // pass in other Google Maps API options here
  },
  internal: {
    id: 'map'
  }
},
function(){
  markers = handler.addMarkers([
    {
      "lat": <%=spot.latitude%>,
      "lng": <%=spot.longitude%>,
      "infowindow": "$<%=spot.price%>: <%=spot.description%>"
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(11);
}
);
</script>
<% end %>
      <% end %>
</div>
</div>
</div>

parking/app/views/spots/new.html.erb
<div class="container">
<div class="row">
  <div class="col-md-6">
    <h2>Create your spot!</h2>
    <%= bootstrap_form_for [@vendor, @spot] do |form| %>
    <div class="row">
      <div class="form-group col-lg-6">
      <%= form.text_field :address %></br>
      <%= form.number_field :zipcode %></br>
      <%= form.number_field :price %></br>
    </div>
    </div>
      <div class="row">
      <div class="form-group col-lg-6">
        <%= form.text_area :description %></br>
        <%= form.file_field :image, label: "Upload your image" %></br>
        <%= form.hidden_field :available, :value => true %></br>
      </div>
      </div>
      <div class="row">
      <div class="form-group col-lg-6">
      <%= form.submit %>
      <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <h2>How to list your parking spot</h2>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
  </div>
</div>

parking/app/views/spots/no_access.html.erb
<h1>You do not have access to this page you must be create a sign up or login.</h1>

parking/app/views/spots/show.html.erb
<p>
  <%= @spots.address%>
  <%= @spots.zipcode %>
  <%= @spots.price %>
  <%= @spots.description %>
</p>
<img src="<%= @spots.image %>" alt="" />


<% if !current_user%>
<p>
  Log in or sign up to reserve this spot
</p>
<% else %>
<%= form_for [@customer, @spots], url: customer_spot_path do |form| %>
<%= form.hidden_field :available, :value => false %></br>
<%= form.hidden_field :customer_id, :value => current_user.id %></br>
<%= form.submit "Reserve this spot" %>
<% end %>
<% end %>

parking/app/views/vendors/index.html.erb
<% @vendors.each do |info| %>

<p><%= info.first_name %> <%= info.last_name %></p>



<% end %>

<%= link_to "Create a listing for your spots", new_vendor_spot_path(@vendors) %>

parking/app/views/vendors/new.html.erb
<h1>Form Page for Vendor</h1>
<h2><%=current_user.id%></h2>

<%= form_for @vendor do |form| %>
  First Name: <%= form.text_field :first_name %></br>
  Last Name: <%= form.text_field :last_name %></br>
  <%= form.hidden_field :id, :value => current_user.id %>
  <%= form.submit %>
<% end %>

parking/app/views/vendors/show.html.erb
<p>
  <%= @vendor.first_name %>
  <%= @vendor.last_name %>
</p>

<%= link_to "Create a listing for your spots", new_vendor_spot_path(@vendor) %>